runtime: custom
env: flex

env_variables:
  GEMINI_API_KEY: YOUR_GEMINI_API_KEY

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10 